name: DragonNiteMC-Lobby
main: com.ericlam.mc.dnmclobby.main.DNMCLobby
version: ${project.version}
api-version: "1.15"
authors: [ericlam]
depend: [ DragoniteMC-Core ]
commands:
  fly:
    aliases: [flight, sky]
    description: fly command
  heal:
    aliases: [blood, medic]
    description: heal command
  hidechat:
    aliases: [chathide, ignoreall, silent, silence]
    description: hide the chat
  stacker:
    aliases: [stack]
    description: open stacker
  speed:
    aliases: [sprint, fast, boost]
    description: speed command
  hideplayer:
    aliases: [hidep]
    description: hide all players
  setting:
    aliases: [playersettings, settings]
    description: open GUI menu
  setlobby:
    aliases: [lobbyset, setspawn]
    description: set the lobby spawn location
  spawn:
    aliases: respawn
    description: teleport to spawn
permissions:
  dragonnite.build:
    description: build perm
    default: false
  donor.join:
    description: donor perm
    default: false
  setting.*:
    description: admin perm
    default: false
  setting.fly:
    default: false
  setting.speed:
    default: false
  setting.stacker:
    default: false
  setting.spawn.other:
    default: false
  setting.hidechat:
    default: false
  setting.hideplayer:
    default: false
  dragonnite.setlobby:
    default: op