General:
  #Saveing-Type 可以是 SQL 或 YAML。
  Saving-Type: yaml
Join-Show-UUID:
  Enable: true
Stacker:
  Enable: true
  Throw-Power: 10
  Throw-Y: 5.0
  Max-Stack: 5
Speed:
  Level: 2
GUI:
  Enable-Notify-On-OpenGUI: true
