name: PlayerSettings
main: main.ericlam.PlayerSettings
version: 1.0
commands:
  fly:
    aliases: [flight, sky, elfly]
    description: fly command
  heal:
    aliases: [blood, elheal]
    description: heal command
  ping:
    aliases: elping
    description: ping command
  hidechat:
    aliases: [chathide, ignoreall, elhidechat]
    description: hide the chat
  stacker:
    aliases: [stack, elstacker]
    description: open stacker
  speed:
    aliases: [elspeed, sprint, fast]
    description: speed command
  hideplayer:
    aliases: [elhideplayer, hidep]
    description: hide all players
permissions:
  ericlam.fly.other:
    default: op
    children:
      ericlam.fly:
        default: op
  ericlam.heal.other:
    default: op
    children:
      ericlam.heal:
        default: op
  ericlam.ping.other:
    default: op
    children:
      ericlam.ping:
        default: true
  ericlam.hidechat.other:
    default: op
    children:
      ericlam.hidechat:
        default: true
  ericlam.stacker.other:
    default: op
    children:
      ericlam.stacker:
        default: true
  ericlam.hideplayer.other:
    default: op
    children:
      ericlam.hideplayer:
        default: true
  ericlam.speed.other:
    default: op
    children:
      ericlam.speed:
        default: true
  ericlam.sneak.showlocation:
    default: true
  ericlam.chat.bypass:
    default: op